---
title: "1_CellCycle_Generalisation_Both"
author: "Yixin Shi"
date: "2026-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(magrittr, ggplot2, ggVennDiagram, pheatmap, ggridges, umap, limma, dplyr, tidyr, viridis, gridExtra, stringr, ggsci, clusterProfiler, UpSetR, missForest,ComplexHeatmap, WGCNA, org.Hs.eg.db, GOSemSim, ggrepel, GSVA, tibble, purrr, scales, imputeLCMD, patchwork, pROC, forcats, scales)
```

# Working Directory
```{r}
rm(list = ls())
getwd()
```
# Load files
```{r}
df <- read.delim(
  "./data/adata_filtered_both_for_R.tsv",
  row.names = 1,
  check.names = FALSE
)
df <- df %>% t %>% as.data.frame()

mr <- sum(is.na(df))/length(as.matrix(df))

df_log2 <- log2(df)
```

# Elbow Point Detection
```{r}
## Filter out protein missing rate >90%
tb_cor <- data.frame(
  missing_rate    = rowSums(is.na(df_log2)) / ncol(df_log2),
  mean_abundance  = rowMeans(df_log2, na.rm = TRUE)
)

geneName1 <- tb_cor %>%
  filter(missing_rate < 0.9) %>%
  rownames(.)

df_filter <- df_log2[geneName1,]

### Data normalization function
median_centering <- function(df) {
  df_norm <- as.data.frame(apply(df, 2, function(x) {
                        gMedian = median(x, na.rm = TRUE)
                        x - gMedian
  }
    ))
  return(df_norm)
}

df_scp <- median_centering(df_filter)


miss_cor <- data.frame(
  missing_rate    = rowSums(is.na(df_scp)) / ncol(df_scp),
  mean_abundance  = rowMeans(df_scp, na.rm = TRUE)
)
### Visualisation
ggplot(miss_cor, aes(x = missing_rate, y = mean_abundance)) +
  geom_point(size = 0.7, alpha = 0.6) +
  geom_smooth(method = "loess", se = FALSE) +
  scale_x_continuous(labels = percent_format(accuracy = 1)) +
  theme_bw() +
  xlab("Missing Rate") +
  ylab("Mean log2 Abundance") +
  ggtitle("Correlation of Abundance and Missing Rate")
```
```{r}
theme_pub <- function(base_size = 10) {
  ggplot2::theme_classic(base_size = base_size) %+replace%
    ggplot2::theme(
      panel.border     = element_rect(colour = "black", fill = NA, linewidth = 0.6),
      axis.title       = element_text(size = base_size + 1, face = "bold"),
      axis.text        = element_text(size = base_size),
      axis.ticks.length= unit(2, "mm"),
      plot.title       = element_text(size = base_size + 2, face = "bold", hjust = 0.5),
      legend.position  = "right",
      legend.title     = element_text(size = base_size),
      legend.text      = element_text(size = base_size - 1)
    )
}

find_missing_rate_elbow <- function(df_norm,
                                    span = 0.75,
                                    n_points = 1000,
                                    point_size = 0.8,
                                    point_alpha = 0.8,
                                    save_path = NULL,   
                                    group_name = NULL,
                                    tiff_width = 6,  
                                    tiff_height = 3.5,
                                    tiff_dpi = 600) {
  
  stopifnot(is.matrix(df_norm) || is.data.frame(df_norm))
  if (!requireNamespace("ggplot2", quietly = TRUE)) stop("Please install 'ggplot2'.")
  if (!requireNamespace("scales", quietly = TRUE))  stop("Please install 'scales'.")
  
  df_norm <- as.matrix(df_norm)
  
  miss_cor <- data.frame(
    missing_rate   = rowSums(is.na(df_norm)) / ncol(df_norm),
    mean_abundance = rowMeans(df_norm, na.rm = TRUE)
  )
  
  fit <- stats::loess(mean_abundance ~ missing_rate, data = miss_cor, span = span)
  
  x_vals <- seq(min(miss_cor$missing_rate, na.rm = TRUE),
                max(miss_cor$missing_rate, na.rm = TRUE),
                length.out = n_points)
  y_vals <- stats::predict(fit, newdata = data.frame(missing_rate = x_vals))
  
  keep   <- !is.na(y_vals)
  x_vals <- x_vals[keep]
  y_vals <- y_vals[keep]
  
  x_start <- x_vals[1];              y_start <- y_vals[1]
  x_end   <- x_vals[length(x_vals)]; y_end   <- y_vals[length(y_vals)]
  line_vec  <- c(x_end - x_start, y_end - y_start)
  norm_line <- sqrt(sum(line_vec^2))
  distances <- vapply(seq_along(x_vals), function(i) {
    point_vec <- c(x_vals[i] - x_start, y_vals[i] - y_start)
    abs(line_vec[1] * point_vec[2] - line_vec[2] * point_vec[1]) / norm_line
  }, numeric(1))
  max_index <- which.max(distances)
  elbow_x <- x_vals[max_index]
  elbow_y <- y_vals[max_index]
  
  library(ggplot2)
  library(scales)
  
  p <- ggplot(miss_cor, aes(x = missing_rate, y = mean_abundance)) +
    geom_point(size = point_size, alpha = point_alpha) +
    geom_smooth(method = "loess", se = FALSE, span = span) +
    geom_abline(
      slope = (y_end - y_start) / (x_end - x_start),
      intercept = y_start - ((y_end - y_start) / (x_end - x_start)) * x_start,
      linetype = "dashed"
    ) +
    geom_point(aes(x = elbow_x, y = elbow_y), color = "red", size = 2) +
    geom_text(
      aes(x = elbow_x, y = elbow_y + 4,
          label = paste0("Elbow @ ", scales::percent(elbow_x, accuracy = 0.001))),
      hjust = -0.2, vjust = -0.5, color = "red",
      size = 6 
    ) +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, by = 0.25),
      labels = scales::percent_format(accuracy = 1)
    ) +
    scale_y_continuous(expand = expansion(mult = c(0.02, 0.05))) +
    labs(
      title = "Elbow Point in 'Dataset CellCycle'",
      x = "Missing Rate",
      y = "Mean log2 Abundance"
    ) +
    theme_pub(base_size = 13) +
  theme(
    axis.title = element_text(face = "bold"),   
    axis.text  = element_text(face = "bold")   
  )
  
  if (!is.null(save_path)) {
    ggsave(filename = save_path, plot = p, device = "tiff",
           dpi = tiff_dpi, width = tiff_width, height = tiff_height,
           units = "in", compression = "lzw")
  }
  
  list(
    miss_cor = miss_cor,
    fit = fit,
    elbow = list(x = elbow_x, y = elbow_y),
    plot = p
  )
}

res_scp <- find_missing_rate_elbow(df_scp, span = 0.75,
                                        save_path = "./figure/scp_elbow.tiff")

res_scp$plot
elbow_x <- res_scp$elbow$x
elbow_y <- as.numeric(res_scp$elbow$y)
```
## Soft Hybrid Imputation Function
```{r}
soft_hybrid_impute <- function(df_rf, df_minProb, df_raw, 
                               r0 = NULL, x0 = NULL, a = 10, b = 5, lambda = 0.4,
                               visualize = TRUE) {
  stopifnot(all(dim(df_rf) == dim(df_minProb)))
  stopifnot(all(rownames(df_rf) == rownames(df_minProb)))

  missing_rate <- rowMeans(is.na(df_raw))
  mean_intensity <- rowMeans(df_raw, na.rm = TRUE)
  r0 <- elbow_x
  x0 <- elbow_y

  sigmoid <- function(x, k, x0) {
    1 / (1 + exp(-k * (x - x0)))
  }
  sigmoid_r <- sigmoid(missing_rate, k = a, x0 = r0)
  sigmoid_x <- sigmoid(mean_intensity, k = b, x0 = x0)
  p_MNAR <- sigmoid_r * (1 - lambda * sigmoid_x)

  df_imp_soft <- df_rf
  for (i in seq_len(nrow(df_rf))) {
    w <- 1 - p_MNAR[i]
    df_imp_soft[i, ] <- w * df_rf[i, ] + (1 - w) * df_minProb[i, ]
  }

  if (visualize) {
    library(ggplot2)
    df_plot <- data.frame(
      Protein = rownames(df_rf),
      MissingRate = missing_rate,
      MeanIntensity = mean_intensity,
      Weight_RF = 1 - p_MNAR
    )
     p <- ggplot(df_plot, aes(x = MissingRate, y = MeanIntensity, color = Weight_RF)) +
        geom_point(size = 0.8, alpha = 0.8) +
        scale_color_gradient(low = "blue", high = "red") +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, by = 0.25),
      labels = scales::percent_format(accuracy = 1)
    ) +
    scale_y_continuous(expand = expansion(mult = c(0.02, 0.05))) +
    labs(
      title = paste("Soft Hybrid Weights in 'Dataset CellCycle'"),
      x = "Missing Rate",
      y = "Mean log2 Abundance"
    ) +
    theme_pub(base_size = 13) +
    theme(
      axis.title = element_text(face = "bold"),  
      axis.text  = element_text(face = "bold"),
      legend.position = c(0.85, 0.75),
      legend.title = element_text(size = 13, face = "bold"),
      legend.text  = element_text(size = 12)   
    )
    print(p)
    ggsave(
      filename = './figure/plot_SH.tiff', 
         plot = p, 
         device = "tiff",
         dpi = 300,
         width = 6, 
         height = 4.5,
         units = "in"
    )
     }
  return(df_imp_soft)
}

```
# Imputation
```{r}
set.seed(123)
# minProb 
#minProb_all <- impute.MinProb(
#  df_scp,
#  q = 0.01,
#  tune.sigma = 1
#)
#save(minProb_all, file = './data/minProb_best_both.Rdata')
load(file = './data/minProb_best_both.Rdata')

# Random forest
#res_all  <- missForest(as.data.frame(df_scp), verbose=FALSE)
#imp_all  <- res_all$ximp
#save(imp_all, file = './data/RF_both.Rdata')
load(file = './data/RF_both.Rdata')

# SoftHybrid
df_imp_soft <- soft_hybrid_impute(imp_all, minProb_all, df_scp, lambda = 0.4)
save(df_imp_soft, file = './data/SoftHybridImputation_best_both.Rdata')
load(file = './data/SoftHybridImputation_best_both.Rdata')

# KNN
#knn_impute <- impute.knn(as.matrix(df_scp), k = 10)
#knn_all <- as.data.frame(knn_impute[[1]])
#save(knn_all, file = './data/knn_best_both.Rdata')
load(file = './data/knn_best_both.Rdata')

# Gaussian
#gaussian_impute <- function(df, width = 0.3, downshift = 1.8) {
#  imputed_df <- df
#  all_values <- unlist(df)
#  observed_values <- all_values[!is.na(all_values)]
  
#  mu <- mean(observed_values, na.rm = TRUE)
#  sigma <- sd(observed_values, na.rm = TRUE)
  
#  impute_mean <- mu - downshift * sigma
#  impute_sd <- sigma * width
  
#  for (i in 1:nrow(df)) {
#    for (j in 1:ncol(df)) {
#      if (is.na(df[i, j])) {
#        imputed_df[i, j] <- rnorm(1, mean = impute_mean, sd = impute_sd)
#      }
#    }
#  }
#  return(imputed_df)
#}
#GS_all <- gaussian_impute(df_scp)
#save(GS_all, file = './data/GS_best_both.Rdata')
load(file = './data/GS_best_both.Rdata')
```

# Save data for Python
```{r}
write.table(
  df_imp_soft,
  file = "./data/SoftHybridImputation_best_both.tsv",
  sep = "\t",
  quote = FALSE,
  col.names = NA
)
write.table(
  minProb_all,
  file = "./data/minProb_best_both.tsv",
  sep = "\t",
  quote = FALSE,
  col.names = NA
)
write.table(
  imp_all,
  file = "./data/RF_best_both.tsv",
  sep = "\t",
  quote = FALSE,
  col.names = NA
)
write.table(
  knn_all,
  file = "./data/knn_best_both.tsv",
  sep = "\t",
  quote = FALSE,
  col.names = NA
)
write.table(
  GS_all,
  file = "./data/GS_best_both.tsv",
  sep = "\t",
  quote = FALSE,
  col.names = NA
)
```

